ALTER TABLE profiles ADD COLUMN IF NOT EXISTS show_read_indicator BOOLEAN DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS check_keys_in_conversations BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS remember_browser BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS disable_auto_uploads BOOLEAN DEFAULT FALSE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vault_pin TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vault_recovery_code TEXT;
